### ISSUE TITLE
Simple alternative

### ISSUE THREAD

**Issue by pldilley** [zkat/proposal-as-patterns#12]
Firstly, I really like this idea, I think using `as` is very nice, in keeping with the `import` syntax.

Me and a colleague were pondering about this at work, and as an afterthought I came up "Named destructure" in my head:
`const name { a, b } = { a: 1, b: 2, c: 3 };   // name ~> { a: 1, b: 2 }`

Theoretically this would also let you access sub-objects:
```
const name { a: { b } } = { a: { b: 2, c: 3 } };
// name ~> { a: { b: 2 } }
// name.a ~> { b: 2 }
```

Thought I'd just throw it out there, although the `as` syntax has won my heart, especially if we can get the whole "restructured" object.

**Comment by ljharb** [comment]
Since you don't have to have `const` or `let` or `var` to destructure, i'm not sure how it would work in those cases.

**Comment by pldilley** [comment]
Well! Let's explore it:

```
let name, a, b;
( name { a: { b } } = { a: { b: 2, c: 3 } } );
console.log(name);   // { a: { b: 2 } }
console.log(a, b);  // { b: 2 }, 2
```

```
(function(name { a: { b } }, c) {
   console.log(name);   // { a: { b: 2 } }
   console.log(a, b);  // { b: 2 }, 2
   console.log(c);  // "Hello"
})( { a: { b: 2, c: 3 } }, "Hello" );
```

etc...

**Personally digging the `as` more though**
Just mentioning this for some thought experimentation.

**Comment by pldilley** [comment]
This is based on my likely understanding as per: https://github.com/zkat/proposal-as-patterns/issues/9

Closing
